name: Build and Publish Caddy with Outline VPN

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Dockerfile
        run: |
          cat << 'EOF' > Dockerfile
          ARG version=2
          FROM caddy:$version-builder AS builder
          RUN xcaddy build --with github.com/Jigsaw-Code/outline-ss-server/outlinecaddy
          FROM caddy:$version
          COPY --from=builder /usr/bin/caddy /usr/bin/caddy
          EOF

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CR }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/outlinecaddy:latest
          platforms: linux/amd64